printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: avoid
proseWrap: always
endOfLine: lf
singleAttributePerLine: true
